### ISSUE TITLE
Idle speed is higher than tap speed.

### ISSUE THREAD

**Issue by reisholmes** [ObliviousGmn/CrkbdBongo#1]
https://github.com/ObliviousGmn/CrkbdBongo/blob/de53725a18e78e769ef4deb171be7cc8962d43b9/bongo.c#L8

Hey! I forked your repo and noticed that you had set the idle speed to be higher than the tap speed, because of this the 'prep' animation never gets played. I thought you'd like to know :)

**Comment by ObliviousGmn** [comment]
Oh wow that would explain it!! Thank you!! I'll fix that right away!
